# Generated by Django 4.2 on 2024-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('movies', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
